config/routes.rb
Shock::Application.routes.draw do

  devise_for :users
  get "welcome/index"

  resources :shows
  resources :products, only: [:create, :edit, :update, :delete]
  get "order/:uuid" => "orders#show", as: :show_order
  get "buy/:sku" => "orders#new", as: :buy
  resource :order, except: [:new, :show]
  post "charges" => "charges#create", as: :charges

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_create :populate_price

  private

  def populate_price
    self.price = self.product.price
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :line_items
  has_many :products, through: :line_items
  belongs_to :customer

  before_create :populate_uuid

  include AASM

  aasm do
    state :new, initial: true
    state :declined, :complete

    event :card_declined do
      transitions from: :new, to: :declined
    end

    event :card_charged do
      transitions from: :new, to: :complete
    end

  end

  def total
    self.line_items.sum :price
  end

  def dl_url
    signer = Aws::S3::Presigner.new
    signer.presigned_url(:get_object, bucket:'shockenaw-downloads', key: self.products.first.file_url)
  end

  private

  def populate_uuid
    self.uuid = SecureRandom.uuid
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items
end

app/models/show.rb
# == Schema Information
#
# Table name: shows
#
#  id         :integer          not null, primary key
#  date       :date
#  venue      :string(255)
#  location   :string(255)
#  info       :text
#  link       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Show < ActiveRecord::Base
  validates :date, :venue, :location, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable,
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  require 'securerandom'

  def create

    @product = Product.find_by sku: params[:sku]
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    shock_customer = Customer.create_with(stripe_id: customer.id)
                         .find_or_create_by(email: params[:stripeEmail])

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @product.price,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    order = Order.create(customer: shock_customer)
    order.products << @product

    OrderMailer.order_email(shock_customer, order).deliver_now

    redirect_to show_order_path(uuid: order.uuid)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @product = Product.find_by sku: params[:sku]
  end

  def show
    @order = Order.find_by(uuid: params[:uuid])
  end

  def create
    @order = Order.create
    @line_item = LineItem.create({
                                  product: Product.find_by(uuid: params[:uuid])
                              })

  end
end

app/controllers/product_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!

  def new

  end

  def create

  end

  def edit

  end

  def update
  end

  def delete
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  before_action :authenticate_user!

  def show

  end
  
  def new
    @show = Show.new
  end

  def create
    @show = Show.new show_params
    if @show.save
      flash[:notice] = "#{@show.date} was successfully created."
      redirect_to root_path
    else
      flash[:error] = @show.errors
      redirect_to root_path
    end
  end

  def edit
    @show = Show.find params[:id]
    render layout: false
  end

  def update
    @show = Show.find params[:id]
    if @show.update show_params
      redirect_to root_path
    end
  end

  def delete

  end

  private

  def show_params
    params.require(:show).permit(:date, :venue, :location, :info, :link)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @shows = Show.where("date >= ?", Date.today).order("date asc")
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $3.99</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Food Locker mp3"
          data-amount="399"
          data-locale="auto"></script>
<% end %>

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :type, collection: ["member bio", "band bio"] %>
  <%= f.button :submit, class: "button small" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  	<meta name="description" content="The web home of the Shockenaw Mountain Boys.  Shockenaw tour dates, bios, photos, and news.  Welcome." />


  	<title>The Shockenaw Mountain Boys</title>

  	<%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag "https://unpkg.com/purecss@1.0.0/build/pure-min.css" %>
    <%= stylesheet_link_tag "https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css" %>
    <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Sancreek" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="header">
      <div class="pure-g">
        <header id="logo" class="pure-u-1">
          <h1><%= link_to "The Shockenaw Mountain Boys", root_path %></h1>
        </header>
      </div>
    </div>
    <div id="body">
      <div class="pure-g">
        <div class="pure-u-1">
          <%= notice %>
          <%= alert %>
        </div>
      </div>
      <%= yield %>
    </div>
    <footer id="footer">
      <div id="footer-links">
        <%= link_to "Site by IBD", "http://www.ignoredbydinosaurs.com" %>
        <% if current_user %>
          | <%= link_to "Add show", "#", data: { "reveal-id" => "show-edit", "reveal-ajax" => new_show_path } %>
          | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          | <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
    </footer>
    <%= javascript_include_tag "application" %>
    <%= yield :closing %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-8646459-10', 'shockenaw.com');
      ga('send', 'pageview');
    </script>
    <div id="show-edit" class="reveal-modal medium" style="display:none"></div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<div>
  <div class="pure-g">
    <div class="pure-u-1">
      <div><%= simple_format @product.description %></div>
      <table class="pure-table" id="order">
        <thead>
        <tr>
          <th>
            Product
          </th>
          <th>
            Price
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>
            <%= @product.title %>
          </td>
          <td>
            $<%= Money.new @product.price %>
          </td>
        </tr>
        </tbody>
      </table>
      <div class="">
        <a id="cc-info-toggle" href="#">CC Payment info</a>
        <div style="display:none" id="cc-info">
          <p>Note: We use a 3rd party credit card processor to handle your transaction.  Your CC
            information is transmitted directly to the processor and at no time does your information touch this website.
            We do not store your credit card number.  Charges are processed via a single use token that is returned from
            the credit card processor for the use of this transaction only.  This token is stored in case the transaction
            fails and needs to be retried later.  If this site were compromised, the token would no longer be valid for
            making charges.</p>
          <p>We take your security very, very seriously.  If you have any further questions about your data on this website
          please reach out to <a href="mailto:grubb@johnnygrubb.com">grubb@johnnygrubb.com</a> directly.</p>
        </div>

      </div>
      <%= form_tag charges_path do %>
        <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-amount="<%= @product.price %>"
        data-description="<%= @product.title %>"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-locale="auto"
        data-zip-code="true">
        </script>
          <%= hidden_field_tag :sku, @product.sku %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="pure-g">
  <div class="pure-u-1">
    <h3>Order # <%= @order.uuid %></h3>
    <p>
      Hi, this is your link for <%= @order.products.first.title %>.
    </p>
    <p>
      <%= link_to "Download here", @order.dl_url, download: @order.products.first.title, class: "pure-button pure-button-primary" %>
    </p>
  </div>

</div>

app/views/product/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/product/delete.html.erb
<h1>Product#delete</h1>
<p>Find me in app/views/product/delete.html.erb</p>

app/views/product/edit.html.erb
<h1>Product#edit</h1>
<p>Find me in app/views/product/edit.html.erb</p>

app/views/shows/_form.html.erb
<div>
  <a class="close-reveal-modal">&#215;</a>
</div>
<div>
  <%= form_for @show, html: { class: "pure-form pure-form-stacked" } do |f| %>
      <div class="input date required large-12 column">
        <%= f.label :date %>
        <%= f.date_field :date, required: true %>
      </div>
      <%= f.label :venue %>
      <%= f.text_field :venue %>

      <%= f.label :location %>
      <%= f.text_field :location %>

      <%= f.label :info %>
      <%= f.text_area :info, input_html: {rows: 6} %>

      <%= f.label :link %>
      <%= f.text_field :link %>


      <%= f.button :submit, class: "button small" %>
  <% end %>
</div>

app/views/shows/edit.html.erb
<%= render 'form' %>

app/views/shows/new.html.erb
<div class="pure-g">
  <div class="pure-u-1">
    <%= render 'form' %>
  </div>
</div>

app/views/welcome/_dudes.html.erb
<div class="dude pure-u-1 pure-u-md-1-2">
  <div class="pad-it">
    <header><h3>John Skehan</h3></header>
    <div class="bio">
      <img src="<%= asset_path 'skehan.jpg' %>" />
      <p>
        John Skehan is a classically trained piano player that took up the mandolin shortly before Railroad Earth got together in 2000.  His mando style often reflects this pianistic, textural style and he's known to spend way too much time in the bathrooms of hotels practicing Bach and shit.  This is the primary reason for the premature graying of many of his bandmates' hair.
      </p>
    </div>
  </div>
</div>
<div class="dude pure-u-1 pure-u-md-1-2">
  <div class="pad-it">
    <header><h3>Andy Goessling</h3></header>
    <div class="bio">
      <img src="<%= asset_path 'andy.jpg' %>" />
      <p>
        Andy grew up as one of the youngest of something like 42 kids and was drafted into one of his older brother's bands when he was 4 years old.  He's known as "the right brain of Railroad Earth", and is close personal friends with numerous TSA agents the world over.  He gets back to his bluegrass roots in the Shockenaw Mountina Boys with the guitar, mando, and banjo.
      </p>
    </div>
  </div>
</div>
<div class="dude pure-u-1 pure-u-md-1-2">
  <div class="pad-it">
    <header><h3>Tim Carbone</h3></header>
    <div class="bio">
      <img src="<%= asset_path 'tim.jpg' %>" />
      <p>
        Violinist.  Producer.  Raconteur.  Many words describe an aspect of Tim Carbone, but none can capture the sweeping breadth of talent embodied in the man.  He's played shows from the deepest hole in Birmingham, AL to playing for his holyness, the Dalai Lama himself.  But if you really want to get to know Tim Carbone, buy him a beer and ask him about his passion for the Boston Red Sox.
      </p>
    </div>
  </div>
</div>
<div class="dude pure-u-1 pure-u-md-1-2">
  <div class="pad-it">
    <header><h3>Johnny Grubb</h3></header>
    <div class="bio">
      <img src="<%= asset_path 'grubb.jpg' %>" />
      <p>
        Johnny Grubb is a renaissance man - a father of 3 beautiful boys, husband to a beautiful wife, world famous bluegrass musician, computer programmer, and all around really great guy to be around at all times.  His wife will attest to this.  He is also the author of this website, and of all these band bios, and clearly misses his former RRE bandmates quite a lot.
      </p>
    </div>
  </div>
</div>

app/views/welcome/_shows.html.erb
<% if @shows.empty? %>
    <h5>Unfortunately...</h5>
    <p>No upcoming shows at this point in time.</p>
<% else %>
    <table id="shows">
      <% @shows.each do |show| %>
          <tr>
            <td><%= show.date.strftime('%B %d') %></td>
            <td><%= show.location %></td>
            <td><%= show.venue %></td>
            <td>
              <%= link_to "details", "#", class: "button radius tiny showinfo", :id => "showinfo-#{show.id}" %>
              <% if current_user %>
                  <br/>
                  <%= link_to "edit", edit_show_path(show), class: "button tiny secondary radius", data: {"reveal-id" => "show-edit", "reveal-ajax" => true} %>
              <% end %>
            </td>
          </tr>
          <tr style="display:none" class="info-row" id="<%= "modal-showinfo-#{show.id}" %>">
            <td colspan="3">
              <%= simple_format show.info %>

            </td>
            <td colspan="1">
              <%= link_to "tickets", show.link, class: "button radius" %>
              <a class="close">&#215;</a>
            </td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/welcome/index.html.erb
<section id="intro">
  <div class="pure-g">
    <div class="pure-u-1">
      <%= image_tag(asset_path 'shock.jpg') %>
    </div>
  </div>
</section>
<section id="info">
  <div class="pure-g">
    <div class="pure-u-1 pure-u-md-2-5">
      <div class="pad-it">
        <h3>the bio</h3>
        <p>The Shockenaw Mountain Boys were formed for fun and profit (so far mostly fun) during the second gulf war.
          Featuring the talents of three current members of the national touring act Railroad Earth and one former
          member and current member of the excellent Emmit-Nershi Band, their performances are legend and by legend I
          mean mostly myth. So if you have the opportunity to see them, you should. It would be like seeing a unicorn...
          sort of.</p>
      </div>
    </div>
    <div class="pure-u-1 pure-u-md-3-5">
      <div class="pad-it">
        <h3>the shows</h3>
        <%= render 'shows' %>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="pure-g">
    <div class="pure-u-1">
      <h3>Some tunes</h3>
    </div>
    <div class="pure-u-1 pure-u-md-1-2">
      <div class="pad-it">
        <%= image_tag 'food_locker.jpg' %>
      </div>
    </div>
    <div class="pure-u-1 pure-u-md-1-2">
      <div class="pad-it">
        <h4>SMB - Food Locker</h4>
        <p>Behold, the long awaited first official release from the Shockenaw Mountain Boys -
          <strong>Food Locker</strong>. Recorded live to a single microphone in July of 2017 during the annual Shawnee
          Riverkeeper canoe trip, Food Locker captures the Shockenaw Boys at their loose, improvisational best.</p>
        <div>

          <ul>
            <% @products.each do |product, idx| %>
              <li>
                <%= link_to product.title, buy_path(product.sku) %> - $<%= Money.new product.price %>
              </li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>
</section>
<section id="news">
  <div class="pure-g">
    <div class="pure-u-1">
      <h3>Some news</h3>
      <div class="flex-video pad-it">
        <iframe width="960" height="540" src="https://www.youtube.com/embed/LXuipghEWNA" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</section>
<section id="members">
  <div class="pure-g">
    <div class="pure-u-1">
      <h2 class="section-header">the dudes</h2>
    </div>
    <%= render 'dudes' %>
  </div>
</section>

<% content_for :closing do %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <script type="text/javascript" charset="utf-8">
//        var handler = StripeCheckout.configure({
//            key: '<%= Rails.configuration.stripe[:publishable_key] %>',
//            locale: 'auto',
//
//            name: 'Food Locker',
//            description: 'Food Locker Download',
//            token: function (token) {
//                $('input#stripeToken').val(token.id);
//                $('form').submit();
//            }
//        });
//        $('.checkout-button').on('click', function(e) {
//          e.preventDefault();
//          var amount = parseInt($(e.currentTarget.form.amount).val());
//          console.log(amount);
//          handler.open({
//              amount: amount
//          });
//        });
//        $('form').submit( function(e) {
//            e.preventDefault();
//            console.log(e);
//        });
    </script>
<% end %>